/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IhgButton {
        "disabled": boolean;
        "label": string;
        "type": 'primary' | 'secondary';
    }
}
declare global {
    interface HTMLIhgButtonElement extends Components.IhgButton, HTMLStencilElement {
    }
    var HTMLIhgButtonElement: {
        prototype: HTMLIhgButtonElement;
        new (): HTMLIhgButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ihg-button": HTMLIhgButtonElement;
    }
}
declare namespace LocalJSX {
    interface IhgButton {
        "disabled"?: boolean;
        "label"?: string;
        "type"?: 'primary' | 'secondary';
    }
    interface IntrinsicElements {
        "ihg-button": IhgButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ihg-button": LocalJSX.IhgButton & JSXBase.HTMLAttributes<HTMLIhgButtonElement>;
        }
    }
}
